Repository availproject/avail, pull requests merged in 2023-10, with the labels that each got.

#250 Switch back to jlumbroso/free-disk-space in CI
  .github/workflows/default.yml
Labels: CI

#211 feat: fix bugs, optimize gas, add attribution
  examples/validium/abi/IDataAvailabilityRouter.json
  examples/validium/abi/ValidiumContract.json
  examples/validium/contracts/ValidiumContract.sol
Labels: bug, enhancement

#264 Serialize block number to hex string on avail_subxt header.
  avail-subxt/src/primitives/header.rs
Labels: bug

#254 `kate-rpc` rewrite + multiproof RPC
  Cargo.lock
  avail-subxt/build_api.sh
  avail-subxt/src/api_dev.rs
  e2e/Cargo.lock
  e2e/Cargo.toml
  e2e/README.md
  e2e/src/main.rs
  rpc/kate-rpc/Cargo.toml
  rpc/kate-rpc/src/lib.rs
Labels: enhancement
